
services:

  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shoe_management
      MYSQL_USER: myroot
      MYSQL_PASSWORD:
    volumes:
      - mysql:/var/lib/mysql
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3306:3306'

  redis:
    image: redis:6.2-alpine
    container_name: redis
    hostname: redis
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB;FLUSHALL
    networks:
      - backend

  api-service:
    container_name: api-service
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8080:80'
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql: